### PR TITLE
Feature/mvp project task5

### PR DESCRIPTION
**Pull request by Leo-95swift**

### CODE REVIEW

**Comment by Leo-95swift** [comment]
https://github.com/Leo-95swift/UIKitTemplate/assets/142137911/28bbff11-0a0d-41a7-9aa7-ab5c8fc8c18b

**Comment by Leo-95swift** [comment]
@Notion

photo_2024-03-08 13 01 21
photo_2024-03-08 13 01 19
photo_2024-03-08 13 01 15
photo_2024-03-08 13 01 12
photo_2024-03-08 13 01 09
photo_2024-03-08 13 01 06
photo_2024-03-08 13 01 02

**Comment by kostjkeee** [comment]
https://github.com/Leo-95swift/UIKitTemplate/assets/142137911/7c9a8778-545b-4ec3-97ab-b6ceef762419

**Comment by Leo-95swift** [comment]
@Notion

Паттерны
Screenshot 2024-03-11 at 12 34 50
Screenshot 2024-03-11 at 12 35 01
Screenshot 2024-03-11 at 12 42 33
Screenshot 2024-03-11 at 12 42 44
Screenshot 2024-03-11 at 12 35 12
Screenshot 2024-03-11 at 12 42 53
Screenshot 2024-03-11 at 12 35 27
Screenshot 2024-03-11 at 12 43 01
Screenshot 2024-03-11 at 12 43 15
Screenshot 2024-03-11 at 12 43 28
Screenshot 2024-03-11 at 12 43 21
Screenshot 2024-03-11 at 12 35 40
Screenshot 2024-03-11 at 12 43 07

**Comment by kostjkeee** [comment]
Screenshot 2024-03-11 at 18 42 59
Screenshot 2024-03-11 at 18 43 02
Screenshot 2024-03-11 at 18 43 05
Screenshot 2024-03-11 at 18 43 08
Screenshot 2024-03-11 at 18 43 11
Screenshot 2024-03-11 at 18 43 13
Screenshot 2024-03-11 at 18 43 16
Screenshot 2024-03-11 at 18 43 19
Screenshot 2024-03-11 at 18 43 21
Screenshot 2024-03-11 at 18 43 24

**Pull request closed without merging**
